### PR TITLE
Add dynamic_transform_publisher

### PR DESCRIPTION
**Pull request by iory**
dynamic transform publisher provides parameter changing by dynamic_reconfigure and interactive markers.

myimage

### CODE REVIEW

**Comment by wjwwood** [comment]
Thanks for the pull request, this is really neat!

I am, however, concerned about merging this into interactive markers directly, as it adds a dependency on dynamic reconfigure. Perhaps it would be better as a standalone package.

Before I review the code, it would be good to see how you feel about keeping it as a separate package. We can, instead, link to your package that does this from the interactive_markers wiki or add a tutorial on how to use it.

**Comment by dgossow** [comment]
I agree with @wjwwood : Really neat tool and thanks for the addition, but it shouldn't be in the (low-level) interactive_markers library.

**Comment by iory** [comment]
@wjwwood @dgossow 
I see. 

>  Perhaps it would be better as a standalone package.

Where should I create a new package?

**Comment by dgossow** [comment]
> Where should I create a new package?

@wjwwood could you weigh in here?

**Comment by wjwwood** [comment]
Uh, I don't have a preference. You can put it on your own organization or we move it to this organization if you like. Either way I think most of the discovery should occur through the wiki and other tools like rosbrowse or the http://rosindex.github.io/ site and not by browsing this organization, so in the end I don't think it matters that much.

**Comment by wkentaro** [comment]
Nice work @iory .

Well, I think it is better to add a package to this organization because it helps people to find it.
(As for me, of course I knew about roswiki, but didn't know about rosindex.github.io.)
It seems that sometimes searching on GitHub returns better results than Google and rosindex.github.io
because we can search inside of code and limit searching range of repositories with organization.
(Getting the top of google and rosindex search is difficult)

I suggest **interactive_marker_server** as the name of package which contains `tf_marker_server` as a node.
Ideally it can also contain [interactive_marker_twist_server/twist_marker_server](https://github.com/ros-visualization/interactive_marker_twist_server).

**Comment by wjwwood** [comment]
As I said, I don't really care how it is organized (I'm not offering to take over maintenance of it), but how do you propose to merge https://github.com/ros-visualization/interactive_marker_twist_server into this new package? Do you know the maintainer (I don't maintain this package)?

You could also just make a package called `interactive_marker_tf_server` on this org.

Either way, sort out what you want to call it and what goes in it (coordinating with existing package maintainers) and let me know where it is and I'll either fork it here or give me permission on it's current location and I'll move it here.

**Comment by wjwwood** [comment]
I'm going to close this in anticipation of it being hosted elsewhere and getting moved into this organization.

**Pull request closed without merging**
