### PR TITLE
Deprecated spin_until_future_complete

### PR DESCRIPTION
**Pull request by hliberacki**
Replace deprecated `spin_until_future_complete` with `spin_until_complete`

Signed-off-by: Hubert Liberacki <hliberacki@gmail.com>

### CODE REVIEW

**Comment by hliberacki** [comment]
Due to change in RCLCPP - https://github.com/ros2/rclcpp/pull/1874 Pull request

**Comment by hliberacki** [comment]
https://github.com/ros2/rclcpp/pull/1874#issuecomment-1086906375 Passing CI with all related PRs linked and build together.

**Comment by hliberacki** [comment]
It looks like This PR is no longer needed - there was only a single `spin_until_future_complete` invocation, which is no longer present.

**Review by SteveMacenski — APPROVED** [review]

**Review by fujitatomoya — APPROVED** [review]

**Comment by Crola1702** [comment]
This PR was merged and caused multiple errors along Rolling CI builds:

* [R_release/633](https://build.ros2.org/view/Rci/job/Rci__nightly-release_ubuntu_jammy_amd64/633/console)
* [R_fastrtps/623](https://build.ros2.org/view/Rci/job/Rci__nightly-fastrtps_ubuntu_jammy_amd64/623/console)
* [R_fastrtps_dynamic/605](https://build.ros2.org/view/Rci/job/Rci__nightly-fastrtps-dynamic_ubuntu_jammy_amd64/605/console)
* [R_coverage/2166](https://ci.ros2.org/job/nightly_linux_coverage/2166/console)

If I'm not wrong, this change was waiting until a pack of other PRs on multiple repositories (https://github.com/ros2/rclcpp/pull/1874#issuecomment-1165688522).

@dgossow was there any reason I'm not seeing to merge this PR right now?

**Comment by Crola1702** [comment]
I think we should wait until https://github.com/ros2/rclcpp/pull/1957 lands (`Revert "Revert"` was a misleading title to understand that's the change we're waiting for :laughing:)

**Pull request merged**
