### PR TITLE
remove useless dependencies

### PR DESCRIPTION
**Pull request by vrabaud**

### CODE REVIEW

**Comment by wjwwood** [comment]
I literally just released this :angry: :smile:

**Comment by wjwwood** [comment]
I'll look at it later.

**Comment by vrabaud** [comment]
I know :) That's how I got interested (I thought it was part of RViz). Then again, that does not deserves a re-release. It compiles for me and I could not find traces of them doing a git grep.

**Comment by wjwwood** [comment]
Ok, this looks good.

**Pull request merged**
