### PR TITLE
[windows] add visibility control and install binaries to portable locations

### PR DESCRIPTION
**Pull request by seanyen**
cherry-pick Windows specific fixes from ROS2:
* Visibility control for shared library:
  * https://github.com/ros-visualization/interactive_markers/pull/44
  * https://github.com/ros-visualization/interactive_markers/pull/51
* Place the shared library to a portable location:
  * https://github.com/ros-visualization/interactive_markers/pull/44 (Adapted to the [catkin](https://docs.ros.org/api/catkin/html/howto/format1/building_libraries.html#installing) convention.)

### CODE REVIEW

**Comment by seanyen** [comment]
@tfoote @dgossow This is ready for review and merge. Thanks!

**Review by dgossow — APPROVED** [review]

**Comment by dgossow** [comment]
lgtm
@tfoote perhaps weigh in if you have additional comments

**Comment by seanyen** [comment]
@tfoote Friendly ping.

**Review by tfoote — APPROVED** [review]

**Comment by dgossow** [comment]
@seanyen merging this to kinetic-devel

**Pull request merged**
