### PR TITLE
avoid dead-lock with locking of the SubscriptionQueue

### PR DESCRIPTION
**Pull request by simonschmeisser**
It looks like I might have introduced a dead-lock with #36 

Basically `InteractiveMarkerClient::process` calls `subscribeInit()` while it still has a lock set on `publisher_contexts_mutex_`. In that function `NodeHandel::subscribe` seems to lock `something`. If another thread handles an incoming message as well and calls `process` as well it will first lock said `something` (read-only) and then tries to lock `publisher_contexts_mutex_`. If those locking attempts occur just in the right moment we get a dead-lock.

It it is very well possible that I'm completely off but I would still appreciate any help and feedback with the following stack trace:

```
Main thread:

Thread 1 (Thread 0x7fe9d22a8340 (LWP 10358)):
#0  __lll_lock_wait () at ../sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:135
No locals.
#1  0x00007fe9f67ab023 in __GI___pthread_mutex_lock (mutex=0x55a28d8a7218) at ../nptl/pthread_mutex_lock.c:78
        ignore1 = <optimized out>
        ignore2 = <optimized out>
        ignore3 = <optimized out>
        type = 0
        __PRETTY_FUNCTION__ = "__pthread_mutex_lock"
        id = <optimized out>
#2  0x00007fe9fa54a9f8 in boost::mutex::lock() () from /opt/isys-vision/mikado/lib/libmoveit_trajectory_execution_manager.so.1.0.5
No symbol table info available.
#3  0x00007fe9f8777d5c in void interactive_markers::InteractiveMarkerClient::process<boost::shared_ptr<visualization_msgs::InteractiveMarkerInit_<std::allocator<void> > const> >(boost::shared_ptr<visualization_msgs::InteractiveMarkerInit_<std::allocator<void> > const> const&) () from /opt/ros/melodic/lib/libinteractive_markers.so
No symbol table info available.
#4  0x00007fe9f87755ae in boost::detail::function::void_function_obj_invoker1<boost::function<void (boost::shared_ptr<visualization_msgs::InteractiveMarkerInit_<std::allocator<void> > const> const&)>, void, boost::shared_ptr<visualization_msgs::InteractiveMarkerInit_<std::allocator<void> > const> >::invoke(boost::detail::function::function_buffer&, boost::shared_ptr<visualization_msgs::InteractiveMarkerInit_<std::allocator<void> > const>) () from /opt/ros/melodic/lib/libinteractive_markers.so
No symbol table info available.
#5  0x00007fe9f8778e86 in ros::SubscriptionCallbackHelperT<boost::shared_ptr<visualization_msgs::InteractiveMarkerInit_<std::allocator<void> > const> const&, void>::call(ros::SubscriptionCallbackHelperCallParams&) () from /opt/ros/melodic/lib/libinteractive_markers.so
No symbol table info available.
#6  0x00007fe9f79d5422 in ros::SubscriptionQueue::call() () from /opt/ros/melodic/lib/libroscpp.so
No symbol table info available.
#7  0x00007fe9f797fb9c in ros::CallbackQueue::callOneCB(ros::CallbackQueue::TLS*) () from /opt/ros/melodic/lib/libroscpp.so
No symbol table info available.
#8  0x00007fe9f7980f8b in ros::CallbackQueue::callAvailable(ros::WallDuration) () from /opt/ros/melodic/lib/libroscpp.so
No symbol table info available.
#9  0x00007fe9f79c18de in ros::spinOnce() () from /opt/ros/melodic/lib/libroscpp.so
No symbol table info available.
#10 0x00007fe9f8dd2e88 in rviz::VisualizationManager::onUpdate() () from /opt/ros/melodic/lib/librviz.so
No symbol table info available.
#11 0x00007fe9fbf7afd5 in QMetaObject::activate(QObject*, int, int, void**) () from /opt/qt512/lib/libQt5Core.so.5
No symbol table info available.
#12 0x00007fe9fbf87e07 in QTimer::timeout(QTimer::QPrivateSignal) () from /opt/qt512/lib/libQt5Core.so.5
No symbol table info available.
#13 0x00007fe9fbf88168 in QTimer::timerEvent(QTimerEvent*) () from /opt/qt512/lib/libQt5Core.so.5
No symbol table info available.
#14 0x00007fe9fbf7bafb in QObject::event(QEvent*) () from /opt/qt512/lib/libQt5Core.so.5
No symbol table info available.
#15 0x00007fe9fb1daebc in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /opt/qt512/lib/libQt5Widgets.so.5
No symbol table info available.
#16 0x00007fe9fb1e2450 in QApplication::notify(QObject*, QEvent*) () from /opt/qt512/lib/libQt5Widgets.so.5
No symbol table info available.
#17 0x00007fe9fbf4b4c8 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /opt/qt512/lib/libQt5Core.so.5
No symbol table info available.
#18 0x00007fe9fbfa7759 in QTimerInfoList::activateTimers() () from /opt/qt512/lib/libQt5Core.so.5
No symbol table info available.
#19 0x00007fe9fbfa7f59 in ?? () from /opt/qt512/lib/libQt5Core.so.5
No symbol table info available.
#20 0x00007fe9f3d84417 in g_main_context_dispatch () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#21 0x00007fe9f3d84650 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#22 0x00007fe9f3d846dc in g_main_context_iteration () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#23 0x00007fe9fbfa82ef in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /opt/qt512/lib/libQt5Core.so.5
No symbol table info available.
#24 0x00007fe9fbf497ea in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /opt/qt512/lib/libQt5Core.so.5
No symbol table info available.
#25 0x00007fe9fbf529a0 in QCoreApplication::exec() () from /opt/qt512/lib/libQt5Core.so.5
No symbol table info available.
#26 0x000055a28b5591c3 in ?? ()
No symbol table info available.
#27 0x00007fe9f5818b97 in __libc_start_main (main=0x55a28b5555d0, argc=3, argv=0x7ffdd57cc538, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffdd57cc528) at ../csu/libc-start.c:310
        self = <optimized out>
        __self = <optimized out>
        result = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {0, 3987214591760944879, 94156610775168, 140728185177392, 0, 0, 7200081462394769135, 7188750008868687599}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x7fe9fdbf2783 <_dl_init+259>, 0x7fe9fdbdfef8}, data = {prev = 0x0, cleanup = 0x0, canceltype = -37804157}}}
        not_first_call = <optimized out>
#28 0x000055a28b56a8aa in ?? ()
No symbol table info available.


A thread of AsyncSpinner:

Thread 11 (Thread 0x7fe9c4bd3700 (LWP 10413)):
#0  __lll_lock_wait () at ../sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:135
No locals.
#1  0x00007fe9f67ab098 in __GI___pthread_mutex_lock (mutex=0x55a295a1ced0) at ../nptl/pthread_mutex_lock.c:113
        ignore1 = <optimized out>
        ignore2 = <optimized out>
        ignore3 = <optimized out>
        id = 10413
        type = 1
        __PRETTY_FUNCTION__ = "__pthread_mutex_lock"
        id = <optimized out>
#2  0x00007fe9f79d6f8f in ros::SubscriptionQueue::clear() () from /opt/ros/melodic/lib/libroscpp.so
No symbol table info available.
#3  0x00007fe9f79cac73 in ros::Subscription::removeCallback(boost::shared_ptr<ros::SubscriptionCallbackHelper> const&) () from /opt/ros/melodic/lib/libroscpp.so
No symbol table info available.
#4  0x00007fe9f795fd51 in ros::TopicManager::unsubscribe(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, boost::shared_ptr<ros::SubscriptionCallbackHelper> const&) () from /opt/ros/melodic/lib/libroscpp.so
No symbol table info available.
#5  0x00007fe9f7920e31 in ros::Subscriber::Impl::unsubscribe() () from /opt/ros/melodic/lib/libroscpp.so
No symbol table info available.
#6  0x00007fe9f7920f4b in ros::Subscriber::Impl::~Impl() () from /opt/ros/melodic/lib/libroscpp.so
No symbol table info available.
#7  0x00007fe9f79224dd in boost::detail::sp_counted_impl_pd<ros::Subscriber::Impl*, boost::detail::sp_ms_deleter<ros::Subscriber::Impl> >::dispose() () from /opt/ros/melodic/lib/libroscpp.so
No symbol table info available.
#8  0x000055a28b570e7a in boost::detail::sp_counted_base::release() ()
No symbol table info available.
#9  0x00007fe9f8773782 in interactive_markers::InteractiveMarkerClient::subscribeInit() () from /opt/ros/melodic/lib/libinteractive_markers.so
No symbol table info available.
#10 0x00007fe9f8778469 in void interactive_markers::InteractiveMarkerClient::process<boost::shared_ptr<visualization_msgs::InteractiveMarkerUpdate_<std::allocator<void> > const> >(boost::shared_ptr<visualization_msgs::InteractiveMarkerUpdate_<std::allocator<void> > const> const&) () from /opt/ros/melodic/lib/libinteractive_markers.so
No symbol table info available.
#11 0x00007fe9f877548e in boost::detail::function::void_function_obj_invoker1<boost::function<void (boost::shared_ptr<visualization_msgs::InteractiveMarkerUpdate_<std::allocator<void> > const> const&)>, void, boost::shared_ptr<visualization_msgs::InteractiveMarkerUpdate_<std::allocator<void> > const> >::invoke(boost::detail::function::function_buffer&, boost::shared_ptr<visualization_msgs::InteractiveMarkerUpdate_<std::allocator<void> > const>) () from /opt/ros/melodic/lib/libinteractive_markers.so
No symbol table info available.
#12 0x00007fe9f87793b6 in ros::SubscriptionCallbackHelperT<boost::shared_ptr<visualization_msgs::InteractiveMarkerUpdate_<std::allocator<void> > const> const&, void>::call(ros::SubscriptionCallbackHelperCallParams&) () from /opt/ros/melodic/lib/libinteractive_markers.so
No symbol table info available.
#13 0x00007fe9f79d5422 in ros::SubscriptionQueue::call() () from /opt/ros/melodic/lib/libroscpp.so
No symbol table info available.
#14 0x00007fe9f797fb9c in ros::CallbackQueue::callOneCB(ros::CallbackQueue::TLS*) () from /opt/ros/melodic/lib/libroscpp.so
No symbol table info available.
#15 0x00007fe9f7980f8b in ros::CallbackQueue::callAvailable(ros::WallDuration) () from /opt/ros/melodic/lib/libroscpp.so
No symbol table info available.
#16 0x00007fe9f79d81f5 in ros::AsyncSpinnerImpl::threadFunc() () from /opt/ros/melodic/lib/libroscpp.so
No symbol table info available.
#17 0x00007fe9f69d1bcd in ?? () from /usr/lib/x86_64-linux-gnu/libboost_thread.so.1.65.1
No symbol table info available.
#18 0x00007fe9f67a86db in start_thread (arg=0x7fe9c4bd3700) at pthread_create.c:463
        pd = 0x7fe9c4bd3700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140642004842240, -7201122725825720593, 140642004837312, 0, 140641589809552, 140642038404160, 7188853806676463343, 7188754347200499439}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
#19 0x00007fe9f5918a3f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
No locals.

```

### CODE REVIEW

**Comment by simonschmeisser** [comment]
@rhaschke may I have your opinion on this please?

**Comment by rhaschke** [comment]
I will have a look later this week if possible.

**Comment by simonschmeisser** [comment]
Thanks, no pressure, I just wasn't sure if you get notifications here as well

**Comment by quarkytale** [comment]
Is this issue still valid or https://github.com/ros-visualization/interactive_markers/pull/103 solved it?

**Comment by simonschmeisser** [comment]
Yes, looks like it :+1:

**Pull request closed without merging**
