### PR TITLE
[Indigo] add explicit keyword argument queue_size for publisher

### PR DESCRIPTION
**Pull request by fmessmer**
I see the following SyntaxWarning when using the InteractiveMarkerServer with Python:

```
/opt/ros/indigo/lib/python2.7/dist-packages/interactive_markers/interactive_marker_server.py:97: SyntaxWarning: The publisher should be created with an explicit keyword argument 'queue_size'. Please see http://wiki.ros.org/rospy/Overview/Publishers%20and%20Subscribers for more information.
  self.init_pub = rospy.Publisher(topic_ns+"/update_full", InteractiveMarkerInit, latch=True)
/opt/ros/indigo/lib/python2.7/dist-packages/interactive_markers/interactive_marker_server.py:98: SyntaxWarning: The publisher should be created with an explicit keyword argument 'queue_size'. Please see http://wiki.ros.org/rospy/Overview/Publishers%20and%20Subscribers for more information.
  self.update_pub = rospy.Publisher(topic_ns+"/update", InteractiveMarkerUpdate)
```

I'm not sure whether this should be fixed and if yes whether the `queue_sizes` I chose are appropriate...so this is open for discussion!
(I chose `queue_size=30` for update as the markers is re-initialized when I set it to only `queue_size=1`. 30 is the default frame_rate in RVIZ.)

### CODE REVIEW

**Comment by dgossow** [comment]
thanks for the fix!

**Comment by fmessmer** [comment]
Hmm...just saw that in the cpp variant the following values are used:

```
 init_pub_ = node_handle_.advertise<visualization_msgs::InteractiveMarkerInit>( init_topic, 100, true );
update_pub_ = node_handle_.advertise<visualization_msgs::InteractiveMarkerUpdate>( update_topic, 100 );
```

@dgossow should we better use the same values (100) for python for consistency?

**Comment by dgossow** [comment]
Good point. Could you do another PR with that change?

**Comment by fmessmer** [comment]
done in #22

**Pull request merged**
