### PR TITLE
fix crash when updates arrives/is processed while shutdown is called

### PR DESCRIPTION
**Pull request by simonschmeisser**
SingleClient is stored in a shared pointer, but this shared pointer was actually never shared
with anybody. So clearing the map will simply delete all instances of SingleClient even if used
in a process/update call

One possible further enhancement would be to add a boolean or extra flag for signaling shutdown and then not handling incoming updates at all

### CODE REVIEW

**Comment by simonschmeisser** [comment]
any comments?

**Comment by simonschmeisser** [comment]
@wjwwood ping?

**Comment by wjwwood** [comment]
Sorry, @simonschmeisser none of us have time to look at it right now. We'll get to it as soon as possible.

**Comment by simonschmeisser** [comment]
@wjwwood ping? Would it make sense for me to become additional maintainer of this/rviz? There seems to be quite a lack of manpower?

**Comment by simonschmeisser** [comment]
@wjwwood I know I'm annoying but: ping?

**Comment by wjwwood** [comment]
@simonschmeisser sorry for the late reply, some how I stopped getting emails on this thread, so I didn't see you offer to help.

We are certainly low on manpower, and I'd definitely be interested in getting help from you on this repository. I have @dhood helping me on rviz already, so maybe if you want to start here and later pick up rviz too if there's not much to do here.

I'll try to review this pr soon, I'm doing my (somewhat annual) passes over these repositories before releasing into melodic.

**Review by wjwwood — APPROVED** [review]
I think the code looks ok, I was considering asking you to use a recursive lock and just lock the entire process, client->process and shutdown methods, but I think this should work ok too. I still need to look into why the CI is failing.

**Comment by wjwwood** [comment]
@simonschmeisser I wonder if the remaining failing test is related to this change, could you check it out quickly to see if it might be the case?

**Comment by wjwwood** [comment]
This failure:

http://build.ros.org/job/Lpr__interactive_markers__ubuntu_xenial_amd64/3/testReport/(root)/InteractiveMarkerClient/init_wait_tf/

**Comment by simonschmeisser** [comment]
No worries and thanks for coming back ;)
I confirmed the failure locally but actually for me it occurs in both my PR and indigo-devel. I'll try to find out what it does.

**Comment by simonschmeisser** [comment]
So by poor mans testing(*) I confirmed that the test in question works except for the last part:

    // send tf info -> message should get passed through
     msg.type=Msg::TF_INFO;
     msg.expect_update_seq_num.push_back(2);
     seq.push_back(msg);
  
since some of the other tests give warnings about unnormalized quaternions I add the following line (152):

      int_marker.pose.orientation.w = 1.0;

it doesn't change anything though

@wjwwood any further ideas? I'll test some more in near future but for today I have to get back to other stuff

* I didn't manage to printf/cout/cerr/ROS_ERROR anything ...

**Comment by simonschmeisser** [comment]
@wjwwood it was actually the unnormalized quaternion in the dummy tf message, it's working now

**Comment by wjwwood** [comment]
> @wjwwood it was actually the unnormalized quaternion in the dummy tf message, it's working now

You're a gentleman and a scholar, I was just getting my VM setup to test it. Thanks for saving me the time :) Sorry for getting you to fix an unrelated test failure, it just seemed plausible that it was related to yours at a glance.

**Review by wjwwood — APPROVED** [review]

**Comment by simonschmeisser** [comment]
@wjwwood would you mind releasing this version to kinetic? (it appears to me that has not happened yet)

**Comment by wjwwood** [comment]
Sure, thanks for your patience:

- Kinetic: https://github.com/ros/rosdistro/pull/18455
- Indigo: https://github.com/ros/rosdistro/pull/18456

**Pull request merged**
