### PR TITLE
Rename enums to avoid collisions with MSVC compiler defines

### PR DESCRIPTION
**Pull request by jacobperron**
Resolves https://github.com/ros2/build_cop/issues/237.

### CODE REVIEW

**Comment by jacobperron** [comment]
Debug:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/8135/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/4123/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/6625/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/8018/)

**Review by cottsay — APPROVED** [review]
CI looks great - thanks for the quick fix!

**Comment by dirk-thomas** [comment]
Doesn't this change API and require existing code to be updated (when ported to ROS 2)? Wouldn't it be another option to undefine the macros on Windows?

**Comment by jacobperron** [comment]
> Doesn't this change API and require existing code to be updated (when ported to ROS 2)? Wouldn't it be another option to undefine the macros on Windows?

The API was already changed in #44. For example, instead of [OK](https://github.com/ros-visualization/interactive_markers/blob/38b97775566c220f17f979d7cc055003efe0c75a/include/interactive_markers/interactive_marker_client.h#L72) in ROS 1, it was changed to INFO (and now STATUS_INFO).

State state variables aren't exposed in ROS 1, were only exposed for testing purposes in ROS 2.

**Comment by jacobperron** [comment]
That being said, I'm also open to undefining the troublesome Windows macros if there's a better argument for that.

**Review by dirk-thomas — APPROVED** [review]
Sounds good to me then.

**Comment by david-vay** [comment]
These should probably be enum classes.

**Comment by jacobperron** [comment]
> These should probably be enum classes.

Not a bad idea. But I don't think it resolves the clash we had with MSVC since it was caused by the preprocessor.

**Comment by david-vay** [comment]
> Not a bad idea. But I don't think it resolves the clash we had with MSVC since it was caused by the preprocessor.

It should resolve that as well, since the names in an enum class are in their own namespace i.e.

```
  enum class Status : uint8_t
  {
    DEBUG = 0,
    INFO,
    WARN,
    ERROR
  };

  void f() {
    Status s1 = Status::INFO;
    Status s2 = INFO; // This will not compile
  }
```

**Comment by jacobperron** [comment]
:thinking: 

I think it would still fail at the declaration:

```
  enum class Status : uint8_t
  {
    DEBUG = 0,  // This is clash with MSVC DEBUG macro
    INFO,
    WARN,
    ERROR  // This will also clash
  };
```

Just a guess, I haven't tried.

**Comment by dgossow** [comment]
you're right, that would be a problem

**Pull request merged**
