### PR TITLE
remove debug statement that could produce segfault

### PR DESCRIPTION
**Pull request by filipjares**
init_it->msg->markers may be empty

### CODE REVIEW

**Comment by dgossow** [comment]
@wjwwood Could you take care of re-releasing interactive_markers? I don't have an installation set up to do this.

**Comment by dgossow** [comment]
@filipjares Thanks for the fix.

**Comment by filipjares** [comment]
@dgossow Thanks for the package (interactive_markers)! ;-)

**Comment by wjwwood** [comment]
@dgossow I can.

**Comment by dgossow** [comment]
Thanks!

**Comment by wjwwood** [comment]
@dgossow does this need to be released into hydro too?

**Comment by dgossow** [comment]
Yes, the hydro branch has the same bug apparently

**Comment by wjwwood** [comment]
Back ported:

13a97b6

**Comment by wjwwood** [comment]
Groovy: https://github.com/ros/rosdistro/pull/2920

**Comment by wjwwood** [comment]
Hydro: https://github.com/ros/rosdistro/pull/2921

**Comment by wjwwood** [comment]
Done.

**Pull request merged**
