### PR TITLE
Port to ROS 2

### LINKED ISSUE #42: Port to ROS 2
I've started a port to ROS 2.

Following a brief discussion in https://github.com/ros-visualization/interactive_markers/pull/41, I'll outline my plans here. Besides the obvious changes to switch to `rclcpp`, I plan to make the following changes:

- Style refactor + enable common ament linter tests (cpplint, uncrustify, flake8, etc ...)
- Use C++11/14 features where appropriate (e.g smart pointers).
- Switch from `tf` to `tf2`
  - Specifically, make use of [`tf2::BufferCoreInterface`](https://github.com/ros2/geometry2/blob/046df60dad728754c434b31f07423fe72db91670/tf2/include/tf2/buffer_core_interface.h#L50) for looking up transforms.
- Add the interactive marker feedback publisher to InteractiveMarkerClient.
    - Previously handled by RViz.
- Replace the "init" topic with a ROS service.
    - It seems more intuitive for clients to request the full state on demand rather than listening to a latched topic (which may have redundant messages queued).
    - We can avoid the logic for clients unsubscribing to the topic after receiving the state.
    - I will prototype a ROS 1 bridge shim to handle the new API.
- Replace the use of the `KEEP_ALIVE` timer with the [Liveliness QoS](https://github.com/ros2/design/blob/f29b7be802d94558beb21c2a916957659c502242/articles/qos_deadline_liveliness_lifespan.md#liveliness) setting.
    - Seems like a natural use of Liveliness and should remove the existing timer-related logic.

I've completed a subset of the points above and will open PRs soon for visibility/review.

Unless there are objections, I will target my PR to a new `ros2` branch of this repository.

### PR DESCRIPTION
**Pull request by jacobperron**
It's a heavy refactor of the original code following the proposal in #42.

This is a work-in-progress, but opening for visibility and early feedback.

Some things still to do:

- Add feedback publisher + API to interactive marker client.
- ~~Add liveliness check between server and client.~~
- Port Python code
- Revisit some TODOs I left in the code
- More tests

Before polishing this, I plan to get it working with the RVIz display and write a standalone node showing how we can bridge with ROS 1.

Resolves #42

Depends on https://github.com/ros2/common_interfaces/pull/70

### CODE REVIEW

**Comment by jacobperron** [comment]
It doesn't seem we need to use liveliness to detect server disconnects, instead we rely on the service client API `service_is_ready()`.

**Comment by jacobperron** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/7974/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/3996/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/6492/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/7826/)

**Comment by jacobperron** [comment]
Attempt to resolve various compiler warnings on macOS and Windows:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/7978/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/4000/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/6497/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/7830/)

**Comment by jacobperron** [comment]
I think this is pretty much ready for review, while I debug the Windows warnings and try to figure out why Clang and GCC disagree on what type something is.

**Review by wjwwood — APPROVED** [review]
All lgtm!

**Comment by jacobperron** [comment]
I think I've worked out all the issues with the Windows build :crossed_fingers: 
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/8035/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/4045/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/6545/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/7893/)

**Review by wjwwood — APPROVED** [review]

**Comment by jacobperron** [comment]
I was so close... but an expected test error message is being picked up as a MSBuild warning :disappointed: [Build Status](https://ci.ros2.org/job/ci_windows/7897/)

**Comment by jacobperron** [comment]
The latest MSBuild warning is a false positive; an instance of https://github.com/ros2/ci/issues/316.

**Comment by jacobperron** [comment]
Windows: [Build Status](https://ci.ros2.org/job/ci_windows/7910/)

**Pull request merged**
